/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
        

import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class Principal extends javax.swing.JFrame {
//Creamos los objectos de tipo Panel para luego añadirlos.
    
   IngresarVehiculo panelIngresarVehiculo;
   RetirarVehiculo panelRetirarVehiculo;

    public IngresarVehiculo getPanelIngresarVehiculo() {
        return panelIngresarVehiculo;
    }

    public RetirarVehiculo getPanelRetirarVehiculo() {
        return panelRetirarVehiculo;
    }

    public PanelListarVehiculos getPanelListarVehiculos() {
        return panelListarVehiculos;
    }
   PanelListarVehiculos panelListarVehiculos;
   
    public Principal() {
        
        //Inicializamos y agregamos los Panel al Frame Principal
       
        initComponents();
        setSize(900,500);
        inicioSesion.setVisible(false);
        panelInicio2.setVisible(true);
        panelIngresarVehiculo=new IngresarVehiculo();
        panelIngresarVehiculo.setBounds(300, 0,500,500);
        add(panelIngresarVehiculo);
        panelIngresarVehiculo.setVisible(false);
        panelRetirarVehiculo=new RetirarVehiculo();
        panelRetirarVehiculo.setBounds(300, 0,500,500);
        add(panelRetirarVehiculo);
        panelRetirarVehiculo.setVisible(false);
        panelListarVehiculos=new PanelListarVehiculos();
        panelListarVehiculos.setBounds(300,0,600,500);
        add(panelListarVehiculos);
        panelListarVehiculos.setVisible(false);
        
    }
    //Metodo para inicio de sesion del sistema 
    public void inicioSesion(){
        String user="rafael";
        String pass="r1990r21";
        if (usuario1.getText().equals(user) && contrasena.getText().equals(pass)){
            inicioSesion.setVisible(false); 
            JOptionPane.showMessageDialog(null,"Bienvenido");
            panelInicio2.setVisible(true);
        
                  }
        
        else{
            JOptionPane.showMessageDialog(null,"Error de usuario o contraseña");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicioSesion = new javax.swing.JPanel();
        contrasena = new javax.swing.JTextField();
        iniciarSesion = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelInicio2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRetirarVehiculo = new java.awt.Button();
        btnIngresarVehiculo = new java.awt.Button();
        btnSalir = new java.awt.Button();
        btnListarVehiculos = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inicioSesion.setBackground(new java.awt.Color(102, 102, 102));
        inicioSesion.setPreferredSize(new java.awt.Dimension(300, 500));
        inicioSesion.setLayout(null);

        contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaActionPerformed(evt);
            }
        });
        inicioSesion.add(contrasena);
        contrasena.setBounds(80, 290, 120, 30);

        iniciarSesion.setBackground(new java.awt.Color(240, 164, 46));
        iniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSesion.setLabel("Ingresar");
        iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionActionPerformed(evt);
            }
        });
        inicioSesion.add(iniciarSesion);
        iniciarSesion.setBounds(100, 350, 83, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Usuario");
        inicioSesion.add(jLabel2);
        jLabel2.setBounds(120, 150, 60, 14);
        inicioSesion.add(usuario1);
        usuario1.setBounds(80, 180, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Contraseña");
        inicioSesion.add(jLabel1);
        jLabel1.setBounds(100, 260, 90, 17);

        panelInicio2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("ParkingSoft");

        btnRetirarVehiculo.setBackground(new java.awt.Color(0, 255, 51));
        btnRetirarVehiculo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnRetirarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirarVehiculo.setLabel("Retirar Vehiculo");
        btnRetirarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarVehiculoActionPerformed(evt);
            }
        });

        btnIngresarVehiculo.setBackground(new java.awt.Color(0, 255, 51));
        btnIngresarVehiculo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnIngresarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarVehiculo.setLabel("Ingresar Vehiculo");
        btnIngresarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarVehiculoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 255, 51));
        btnSalir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setLabel("Salir");

        btnListarVehiculos.setBackground(new java.awt.Color(0, 255, 51));
        btnListarVehiculos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnListarVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnListarVehiculos.setLabel("Listar Vehiculos");
        btnListarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVehiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInicio2Layout = new javax.swing.GroupLayout(panelInicio2);
        panelInicio2.setLayout(panelInicio2Layout);
        panelInicio2Layout.setHorizontalGroup(
            panelInicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicio2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicio2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelInicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panelInicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetirarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        panelInicio2Layout.setVerticalGroup(
            panelInicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicio2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(panelInicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRetirarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(panelInicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionActionPerformed
         inicioSesion();
    }//GEN-LAST:event_iniciarSesionActionPerformed

    private void contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaActionPerformed

    private void btnIngresarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarVehiculoActionPerformed
       panelIngresarVehiculo.setVisible(true);
       panelListarVehiculos.setVisible(false);
       panelRetirarVehiculo.setVisible(false);
    }//GEN-LAST:event_btnIngresarVehiculoActionPerformed

    private void btnRetirarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarVehiculoActionPerformed
       panelIngresarVehiculo.setVisible(false);
       panelListarVehiculos.setVisible(false);
       panelRetirarVehiculo.setVisible(true);
    }//GEN-LAST:event_btnRetirarVehiculoActionPerformed

    private void btnListarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVehiculosActionPerformed
       panelIngresarVehiculo.setVisible(false);
       panelListarVehiculos.setVisible(true);
       panelRetirarVehiculo.setVisible(false);
    }//GEN-LAST:event_btnListarVehiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Button btnIngresarVehiculo;
    public java.awt.Button btnListarVehiculos;
    public java.awt.Button btnRetirarVehiculo;
    public java.awt.Button btnSalir;
    private javax.swing.JTextField contrasena;
    private java.awt.Button iniciarSesion;
    private javax.swing.JPanel inicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelInicio2;
    private javax.swing.JTextField usuario1;
    // End of variables declaration//GEN-END:variables
}
